config/routes.rb
Unclaimedproperty::Application.routes.draw do
  root to: 'welcome#index'
  get '/about',    to: 'welcome#about'
  get '/contact',    to: 'welcome#contact'
  resources :notifications
  resources :properties do
    collection do
      get 'name/:name', to: 'properties#name_search', as: 'name_search'
      get 'zip/:zip', to: 'properties#zip_search'
    end
  end
  get 'lookup_name', :to => 'properties#lookup_name'
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    limit = Rails.env == "production" ? 200 : 10
    @properties = Property.most_recent(20).where("cash_report > #{limit}")
    @notification = Notification.new
  end

  def about
    @notification = Notification.new
  end
end

app/views/welcome/about.html.haml
%h1 What we do and what you get

%p.lead
  %b What we do:
  Every week we're downloading all the new properties listed on the #{link_to "California Unclaimed Property Search", "http://sco.ca.gov/upd.html"}.  Yes, we're the only people who do this.  Yes, we are #{link_to "programmers", "http://www.stevenhallen.com/who-we-are/"}.

%p.lead
  %b What you get:
  You'll get an email if your name ever appears in one of these records.  That's pretty much it.
  
%p.lead
  %b Why?
  We're into data and #{link_to "solving problems", "http://stevenhallen.com"}, plus, we think some people might be interested in paying us for this service (eventually).
= render :partial => 'notifications/form'

app/views/welcome/contact.html.haml
%h1 Contact Us

%p.lead We develop software solutions.
%p.lead
  %b Email:
  =mail_to "info@stevenhallen.com"
%p.lead
  %b Web:
  =link_to "Steven H. Allen & Co.", "http://stevenhallen.com"

app/views/welcome/index.html.haml
.hero-unit
  %h1 Let us search for you
  %br
  %h3
    Forget about continually checking the 
    #{link_to "California unclaimed property search", "http://sco.ca.gov/upd.html"}.
  %p.lead
    We will do that for you.
  %p
    = link_to 'Sign Up &#187;'.html_safe, "/about", :class => 'btn btn-success btn-large'
    = link_to 'Learn More &#187;'.html_safe, "/about", :class => 'btn btn-primary btn-large'
      

.row
  .span6
    %h2 Latest Unclaimed CA Property
    %table.table
      - @properties.each do |property|
        %tr
          %td
            = link_to "#{property.first_name} #{property.middle_name} #{property.last_name}", property_path(property)
          %td
            #{property.city}, #{property.state}
            
          %td
            = number_to_currency(property.cash_report)
    %p.lead There's a whole lot more, this is just a sample.
            
  .span6
    %h2 Sign Up To Receive Notifications
    = render :partial => 'notifications/form'
    %br
    %h2 Search Properties
    = render :partial => 'shared/name_search'